version: '3'

services:
   dnsmasq:
     container_name: dnsmasq
     image: ilmuflone/dnsmasq:2.89-archlinux-base-20230730
     hostname: dnsmasq
     # Use network_mode: host to enable DHCP
     network_mode: host
     ports:
       - 53:53/udp
     cap_add:
       - NET_ADMIN
     restart: 'unless-stopped'
     volumes:
       - ./dnsmasq.conf:/etc/dnsmasq.conf
       - ./data:/etc/dnsmasq.d
       - ./dnsmasq.leases:/var/lib/misc/dnsmasq.leases

