name: Build and publish image

on:
  push:
    branches:
      - main    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Define variables
      run: |
        echo "PACKAGE_NAME=docker-dnsmasq" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$(git describe --tags --abbrev=0).$(git rev-list --count HEAD)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        docker build archlinux-base --tag ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }} --tag ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:latest
    - name: Push to registry
      run: |
        docker login -u "${{ secrets.DOCKER_REGISTRY_USER }}" -p "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" "${{ vars.DOCKER_REGISTRY_REPOSITORY }}"
        docker push ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }}
        docker push ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:latest
