name: Build and publish image

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Define variables
      run: |
        echo "COMMIT_REVISION=$(git rev-list --count HEAD)" >> $GITHUB_ENV
        echo "PACKAGE_NAME=docker-dnsmasq" >> $GITHUB_ENV
        echo "PACKAGE_DATE=$(date +%Y%m%d.%H%M%S)" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=${PACKAGE_DATE}.${COMMIT_REVISION}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        docker build archlinux-base --tag ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }} --tag ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:latest
    - name: Push to registry
      run: |
        docker login -u "${{ secrets.DOCKER_REGISTRY_USER }}" -p "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" "${{ vars.DOCKER_REGISTRY_REPOSITORY }}"
        docker push ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:${{ env.PACKAGE_VERSION }}
        docker push ${{ vars.DOCKER_REGISTRY_REPOSITORY }}/${{ env.PACKAGE_NAME }}:latest
